version: '2'

volumes:
  data:
  db:

services:
# mariaDB Container
  db:
    image: mariadb:11.1-jammy
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
# It is strongly recommended to change these identifiers by other more secure ones.
# Don't forget to report them in the app service below.
      - MYSQL_ROOT_PASSWORD=rtpsw
      - MYSQL_PASSWORD=zmpass
      - MYSQL_DATABASE=zm
      - MYSQL_USER=zmuser

#GLPI Container
  app:
    image: jantman/docker-zoneminder
    restart: always
    ports:
      - 80:80
    links:
      - db
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./cache:/var/cache/zoneminder
      - ./log:/var/log/zm
