version: '2'

volumes:
  data:
  db:

services:
  mariadb:
    image: mariadb:11.1-jammy
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=zmpass
      - MYSQL_DATABASE=zm
      - MYSQL_USER=zmuser
      - MARIADB_ROOT_PASSWORD=w8t67u23789t
  zm:
    image: jantman/docker-zoneminder:devel
    restart: always
    ports:
      - 80:80
    links:
      - mariadb
    volumes:
      - ./cache:/var/cache/zoneminder
      - ./log:/var/log/zm
