#!/bin/bash
# ==============================================================================
# ZoneMinder
# Runs ZoneMinder
# ==============================================================================

echo "Starting ZoneMinder..."
if [[ "${STRACE_ZMPKG}" == "true" ]]; then
    s6-setuidgid www-data strace -ff -o /var/log/zm/strace /usr/bin/zmpkg.pl start
else
    su -c '/usr/bin/zmpkg.pl start' -s /bin/bash www-data
fi

# zmpkg.pl is blocking so no need to wait
echo "ZoneMinder is up! Proceeding to monitoring."

# Need to sleep to act like service is running
# Terminate container if zm dies
until [ "$(pgrep -fc /usr/bin/zm)" -lt "1" ]; do
  sleep 1
done
ps aux
>&2 echo "ZoneMinder has crashed! Exiting..."
exit 1
